sudo: false
language: node_js
node_js:
    - "13"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm run lint
    - npm run coveralls

jobs:
    include:
        - stage: npm release
        node_js: "13"
        script: 
            - npm run build
        after_success:
        #     - npm run semantic-release
            - ls -la
        # deploy:
        #     provider: npm
        #     email: "$NPM_EMAIL"
        #     api_key: "$NPM_TOKEN"
        #     skip_cleanup: true
        #     on:
        #         tags: true
        #         branch: master