language: node_js

node_js:
  - node

branches:
  only:
    - master

cache:
  npm: false
  directories:
    - ~/.pnpm-store

before_install:
  - curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

script:
  - pnpm lint
  - pnpm test
  - pnpm coveralls
  - pnpm build
  
after_success:
  - pnpm semantic-release
